---
- name: setup local machine
  hosts: localhost
  connection: local
  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user_dir: "/home/{{ ansible_user }}"
  roles:
    - role: swap
    - role: google_chrome
    - role: slack
    - role: code
    - role: ibus-mozc
    - role: ghq
    - role: tmux
    - role: docker
    - role: fish
    - role: fzf
    - role: caps_lock_to_ctrl
    - role: cloudflared
    - role: zoom
    # - role: autoware
